name: Check code style

on:
  pull_request:
  push:
    paths:
      - '**.php'

jobs:
  php-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check style
        uses: aglipanci/laravel-pint-action@v2
        with:
          testMode: true
