name: Run tests

on:
  - push
  - pull_request

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3']
        laravel: ['6.*', '7.*', '8.*', '9.*', '10.*', '11.*']
        stability: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 6.*
            php: '8.1'
          - laravel: 6.*
            php: '8.2'
          - laravel: 6.*
            php: '8.3'
          - laravel: 7.*
            php: '8.1'
          - laravel: 7.*
            php: '8.2'
          - laravel: 7.*
            php: '8.3'
          - laravel: 8.*
            php: '8.2'
          - laravel: 8.*
            php: '8.3'
          - laravel: 9.*
            php: '7.4'
          - laravel: 9.*
            php: '8.3'
          - laravel: 10.*
            php: '7.4'
          - laravel: 10.*
            php: '8.0'
          - laravel: 11.*
            php: '7.4'
          - laravel: 11.*
            php: '8.0'
          - laravel: 11.*
            php: '8.1'

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ matrix.stability }}-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ matrix.stability }}-

      - name: Install dependencies
        run: |
          composer require "illuminate/console:${{ matrix.laravel }}" "illuminate/contracts:${{ matrix.laravel }}" "illuminate/database:${{ matrix.laravel }}" "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text
